package com.sis.project.model;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "employees")
public class Role
{

    private Integer roleId;
    private String name;
    private Byte active;
    private List<User> users = new ArrayList<>();

    public Role()
    {
    }

    public Role(String name, Byte active, List<User> users)
    {
        this.name = name;
        this.active = active;
        this.users = users;
    }

    @Column(name = "active")
    public Byte getActive()
    {
        return active;
    }

    @Column(name = "name", length = 45)
    public String getName()
    {
        return name;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "role_id", unique = true, nullable = false)
    public Integer getRoleId()
    {
        return roleId;
    }

    @ManyToMany(fetch = FetchType.EAGER, mappedBy = "roles")
    public List<User> getUsers()
    {
        return users;
    }

    public void setActive(Byte active)
    {
        this.active = active;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public void setRoleId(Integer roleId)
    {
        this.roleId = roleId;
    }

    public void setUsers(List<User> users)
    {
        this.users = users;
    }

}
