package com.sis.project.model;

import com.sis.project.utils.GenderEnum;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "employees")
public class User
{

    private Integer userId;
    @NotEmpty
    private String firstName;
    @NotEmpty
    private String lastName;
    @NotEmpty
    @Size(min = 11, max = 11)
    private String oib;
    @NotNull
    private GenderEnum gender;
    @DateTimeFormat(pattern = "dd.MM.yyyy")
    @NotNull
    private Date dateOfBirth;
    @NotEmpty
    private String birthPlace;
    @NotEmpty
    private String citizenship;
    private String username;
    private String password;
    @NotEmpty
    private String email;
    private byte[] avatar;
    private Byte active;
    private List<Role> roles = new ArrayList<>();

    public User()
    {
    }

    public User(String firstName, String lastName, String oib, GenderEnum gender, Date dateOfBirth, String birthPlace, String citizenship, String username, String password, String email, byte[] avatar, Byte active, List<Role> roles)
    {
        this.firstName = firstName;
        this.lastName = lastName;
        this.oib = oib;
        this.gender = gender;
        this.dateOfBirth = dateOfBirth;
        this.birthPlace = birthPlace;
        this.citizenship = citizenship;
        this.username = username;
        this.password = password;
        this.email = email;
        this.avatar = avatar;
        this.active = active;
        this.roles = roles;
    }

    @Column(name = "active")
    public Byte getActive()
    {
        return active;
    }

    @Column(name = "avatar")
    public byte[] getAvatar()
    {
        return avatar;
    }

    @Column(name = "birth_place", length = 45)
    public String getBirthPlace()
    {
        return birthPlace;
    }

    @Column(name = "citizenship", length = 45)
    public String getCitizenship()
    {
        return citizenship;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "date_of_birth", length = 10)
    public Date getDateOfBirth()
    {
        return dateOfBirth;
    }

    @Column(name = "email", length = 45)
    public String getEmail()
    {
        return email;
    }

    @Column(name = "first_name", length = 45)
    public String getFirstName()
    {
        return firstName;
    }

    @Column(name = "gender")
    public GenderEnum getGender()
    {
        return gender;
    }

    @Column(name = "last_name", length = 45)
    public String getLastName()
    {
        return lastName;
    }

    @Column(name = "oib", length = 45)
    public String getOib()
    {
        return oib;
    }

    @Column(name = "password")
    public String getPassword()
    {
        return password;
    }

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "user_roles", catalog = "employees", joinColumns = { @JoinColumn(name = "user_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "role_id", nullable = false, updatable = false) })
    public List<Role> getRoles()
    {
        return roles;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "user_id", unique = true, nullable = false)
    public Integer getUserId()
    {
        return userId;
    }

    @Column(name = "username", length = 45)
    public String getUsername()
    {
        return username;
    }

    public void setActive(Byte active)
    {
        this.active = active;
    }

    public void setAvatar(byte[] avatar)
    {
        this.avatar = avatar;
    }

    public void setBirthPlace(String birthPlace)
    {
        this.birthPlace = birthPlace;
    }

    public void setCitizenship(String citizenship)
    {
        this.citizenship = citizenship;
    }

    public void setDateOfBirth(Date dateOfBirth)
    {
        this.dateOfBirth = dateOfBirth;
    }

    public void setEmail(String email)
    {
        this.email = email;
    }

    public void setFirstName(String firstName)
    {
        this.firstName = firstName;
    }

    public void setGender(GenderEnum gender)
    {
        this.gender = gender;
    }

    public void setLastName(String lastName)
    {
        this.lastName = lastName;
    }

    public void setOib(String oib)
    {
        this.oib = oib;
    }

    public void setPassword(String password)
    {
        this.password = password;
    }

    public void setRoles(List<Role> roles)
    {
        this.roles = roles;
    }

    public void setUserId(Integer userId)
    {
        this.userId = userId;
    }

    public void setUsername(String username)
    {
        this.username = username;
    }

}
